### ISSUE TITLE
deploy `portal-dashboard` app in Sage Shiny server

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/syndccutils#42]
Now that we have a (mostly) working version of the portal summary dashboard, we should figure out how to host it through our Shiny server. According to @sgosline, both @xindiguo and @teslajoy know how to do this...

**Comment by teslajoy** [comment]
will do - I'll get this going on site early am tomorrow. 
I have emailed Xa about a non-fredhutch server space. May need to move after the move.

**Comment by teslajoy** [comment]
add login to synapse wrapper. note to self.
