### ISSUE TITLE
Non-ASCII characters

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/syndccutils#82]
`augment_values()` currently uses the non-ASCII character `—` (em dash) to separate meta and target columns. R CMD check throws a warning about the non-ASCII character. We could resolve this either by using the unicode escape `\u2014` or by replacing the em dash with `-` (hyphen-minus), which would result in a subtly different appearance:

```
## Before
# A tibble: 2 x 2
  col_x col_y    
  <chr> <chr>    
1 foo   foo — bar
2 bar   bar — baz

## After
# A tibble: 2 x 2
  col_x col_y    
  <chr> <chr>    
1 foo   foo - bar
2 bar   bar - baz
```

@jaeddy do you have a preference on which option to go with?

**Comment by jaeddy** [comment]
Hmm... I do like my em dashes, but the unicode might be more trouble than it's worth. I think we can go with the simple hyphen for now.
